# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cade_api_pb2 as cade__api__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cade_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CadeRemoteStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/cade_api.rpc.CadeRemote/Info',
                request_serializer=cade__api__pb2.InfoRequest.SerializeToString,
                response_deserializer=cade__api__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/cade_api.rpc.CadeRemote/Pause',
                request_serializer=cade__api__pb2.PauseRequest.SerializeToString,
                response_deserializer=cade__api__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.SetFogOfWar = channel.unary_unary(
                '/cade_api.rpc.CadeRemote/SetFogOfWar',
                request_serializer=cade__api__pb2.SetFogOfWarRequest.SerializeToString,
                response_deserializer=cade__api__pb2.SetFogOfWarResponse.FromString,
                _registered_method=True)
        self.SetPerspective = channel.unary_unary(
                '/cade_api.rpc.CadeRemote/SetPerspective',
                request_serializer=cade__api__pb2.SetPerspectiveRequest.SerializeToString,
                response_deserializer=cade__api__pb2.SetPerspectiveResponse.FromString,
                _registered_method=True)
        self.Frames = channel.unary_stream(
                '/cade_api.rpc.CadeRemote/Frames',
                request_serializer=cade__api__pb2.FramesRequest.SerializeToString,
                response_deserializer=cade__api__pb2.FrameSequence.FromString,
                _registered_method=True)


class CadeRemoteServicer:
    """Missing associated documentation comment in .proto file."""

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFogOfWar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPerspective(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Frames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CadeRemoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=cade__api__pb2.InfoRequest.FromString,
                    response_serializer=cade__api__pb2.InfoResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=cade__api__pb2.PauseRequest.FromString,
                    response_serializer=cade__api__pb2.PauseResponse.SerializeToString,
            ),
            'SetFogOfWar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFogOfWar,
                    request_deserializer=cade__api__pb2.SetFogOfWarRequest.FromString,
                    response_serializer=cade__api__pb2.SetFogOfWarResponse.SerializeToString,
            ),
            'SetPerspective': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPerspective,
                    request_deserializer=cade__api__pb2.SetPerspectiveRequest.FromString,
                    response_serializer=cade__api__pb2.SetPerspectiveResponse.SerializeToString,
            ),
            'Frames': grpc.unary_stream_rpc_method_handler(
                    servicer.Frames,
                    request_deserializer=cade__api__pb2.FramesRequest.FromString,
                    response_serializer=cade__api__pb2.FrameSequence.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cade_api.rpc.CadeRemote', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cade_api.rpc.CadeRemote', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CadeRemote:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cade_api.rpc.CadeRemote/Info',
            cade__api__pb2.InfoRequest.SerializeToString,
            cade__api__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cade_api.rpc.CadeRemote/Pause',
            cade__api__pb2.PauseRequest.SerializeToString,
            cade__api__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFogOfWar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cade_api.rpc.CadeRemote/SetFogOfWar',
            cade__api__pb2.SetFogOfWarRequest.SerializeToString,
            cade__api__pb2.SetFogOfWarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPerspective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cade_api.rpc.CadeRemote/SetPerspective',
            cade__api__pb2.SetPerspectiveRequest.SerializeToString,
            cade__api__pb2.SetPerspectiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Frames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cade_api.rpc.CadeRemote/Frames',
            cade__api__pb2.FramesRequest.SerializeToString,
            cade__api__pb2.FrameSequence.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
